export const ImagePath = {
  oneCareLogo: require('../assets/images/OneCareLogo.svg'),
  landingOne: require('../assets/images/LandingOne.svg'),
  landingTwo: require('../assets/images/LandingTwo.svg'),
  landingThree: require('../assets/images/LandingThree.svg'),
  landingFour: require('../assets/images/LandingFour.svg'),
  backArrow: require('../assets/images/BackArrow.svg'),
  home: require('../assets/images/Home.svg'),
  weekPlan: require('../assets/images/WeekPlan.svg'),
  journal: require('../assets/images/Journal.svg'),
  profile: require('../assets/images/Profile.svg'),
  info: require('../assets/images/info.svg'),
  videoPlay: require('../assets/images/videoPlay.svg'),
  downArrow: require('../assets/images/downArrow.svg'),
  rightArrow: require('../assets/images/rightArrow.svg'),
  activityFrame: require('../assets/images/activityFrame.png'),
  star: require('../assets/images/star.svg'),
  addButton: require('../assets/images/addButton.svg'),
  diet: require('../assets/images/diet.svg'),
  sleep: require('../assets/images/sleep.svg'),
  hba1cTest: require('../assets/images/hba1cTest.svg'),
  weight: require('../assets/images/weight.svg'),
  steps: require('../assets/images/steps.svg'),
  physicalActivity: require('../assets/images/physicalActivity.svg'),
  bloodSugar: require('../assets/images/bloodSugar.svg'),
  dietPDF: require('../assets/images/dietPDF.png'),
  cross: require('../assets/images/cross.svg'),
  stop: require('../assets/images/stop.svg'),
  keep: require('../assets/images/keep.svg'),
  start: require('../assets/images/start.svg'),
  newWeekPlan: require('../assets/images/newWeekPlan.png'),
  redFrame: require('../assets/images/redFrame.png'),
  violetFrame: require('../assets/images/violetFrame.png'),
  greenFrame: require('../assets/images/greenFrame.png'),
  orangeFrame: require('../assets/images/orangeFrame.png'),
  blueFrame: require('../assets/images/blueFrame.png'),
  chat: require('../assets/images/chat.svg'),
  persons: require('../assets/images/persons.svg'),
  camera: require('../assets/images/camera.svg'),
  groupImage: require('../assets/images/groupImage.png'),
};

export const Colors = {
  white: '#FFFFFF',
  black: '#000000',
  screenBackground: '#F4FBFD',
  buttonBackground: '#F07162',
  separator: '#D9D9D9',
  placeholder: '#BFBFBF',
  lightGrey: '#8C8C8C',
  orange: '#F8A524',
  green: '#389E0D',
  textGreen: '#00A591',
  textBlue: '#23AFD7',
  buttonLinearOne: '#FAAF23',
  buttonLinearTwo: '#F0647D',
  greenLinear1: '#00A591',
  greenLinear2: '#00A591BF',
  blueLinear1: '#23AFD7',
  blueLinear2: '#23AFD7BF',
  pinkLinear1: '#F0647D',
  pinkLinear2: '#F0647DBF',
  borderColor: '#DADADA',
  blackLight: '#595959',
};

export const Fonts = {
  SFPro: 'SFProText-Regular',
};
